### ISSUE TITLE
The "Building My First Package" docs don't work

### ISSUE THREAD

**Issue by 0atman** [finkel-lang/finkel#1]
### General summary/comments

Example finkel package doesn't seem to work.

### Steps to reproduce
Following https://finkel.readthedocs.io/en/latest/contents/building-package.html

### Expected

I hoped to build my own finkel project with stack-managed dependencies

### Actual

What actually happened.

```
$ tree
.
├── package.yaml
├── Setup.hs
└── src
    └── MyFirstPackage.fnk

1 directory, 3 files
```

```
$ stack build my-first-package

Error: While constructing the build plan, the following exceptions were encountered:

Unknown package: my-first-package

Some different approaches to resolving this:

Plan construction failed.
```

### Finkel version and environment information

I used this package.yaml, as per the docs
```yaml
name: my-first-package
version: 0.1.0.0

extra-source-files:
  - src/**.fnk

custom-setup:
  dependencies:
    - base
    - Cabal
    - finkel-tool

library:
  source-dirs: src
  exposed-modules: MyFirstPackage
  build-tools:
    - finkel-tool:finkel
  dependencies:
    - base
```

*  Ubuntu 19.04, specifically `Linux 5.3.0-40-lowlatency #32-Ubuntu SMP PREEMPT Fri Jan 31 21:48:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Stack Version 2.1.3

### Method of installation

* Via stack, via git
